name: Publish Docker image

on:
  release:
    types: ["published"]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Log in to container registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login  -u ${{ github.repository_owner }} --password-stdin git.gay


      - name: Build container
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: https://github.com/docker/metadata-action@v3
        with:
          images: git.gay/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        run: |
          docker push ${{ steps.meta.outputs.tags }}
